//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Program
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answers
    {
        public int Id_Answer { get; set; }
        public string answer { get; set; }
        public string status_answer { get; set; }
        public int id_quest { get; set; }
    
        public virtual Questions Questions { get; set; }
    }
}
