//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Program
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenceBookEntries
    {
        public int Id_Entries { get; set; }
        public string topic_Entries { get; set; }
        public string description_Entries { get; set; }
        public string image_Entries { get; set; }
        public string link_Entries { get; set; }
    }
}
