//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Program
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezults
    {
        public int Id_Rezult { get; set; }
        public int percent { get; set; }
        public string countRightQuestions { get; set; }
        public int grade { get; set; }
        public string date { get; set; }
        public int id_user { get; set; }
        public int id_test { get; set; }
    
        public virtual Tests Tests { get; set; }
        public virtual Users Users { get; set; }
    }
}
